[tools]
pre-commit = "latest"
python = "3.13"
uv = "latest"
trivy = "0.69.3"
ruff = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'study-tracker'
GITOPS_REPO = 'study-tracker-gitops'


[hooks]
enter = """
mise install
mise reshim
git config --global push.autoSetupRemote true
git config --global --add safe.directory /workspaces/study-tracker
mise exec -- pip install --user pipx
mise exec -- pipx install commitizen
mise exec -- pre-commit install
mise exec -- pre-commit install --hook-type commit-msg
"""
